version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: biblioteca-db
    environment:
      - ORACLE_PASSWORD=Admin123Password
    ports:
      - "1521:1521"
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: unless-stopped

  bff-service:
    build: 
      context: ./bff-service
      dockerfile: Dockerfile
    container_name: biblioteca-bff
    ports:
      - "8080:8080"
    environment:
      # ¡AQUÍ VAN TUS URLS DE AZURE! 
      # Reemplaza estas de ejemplo por las tuyas reales
      - URL_FUNCION_USUARIOS=https://biblio-users-g11.azurewebsites.net/api/usuarios
      - URL_FUNCION_PRESTAMOS=https://biblio-prestamos-g11.azurewebsites.net/api/prestamos
    depends_on:
      - oracle-db
    restart: unless-stopped