services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: biblioteca-db
    environment:
      - ORACLE_PASSWORD=Admin123Password
      - APP_USER=biblioteca
      - APP_USER_PASSWORD=Biblioteca123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./database/db.sql:/container-entrypoint-initdb.d/db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  bff-service:
    build:
      context: ./bff-service
      dockerfile: Dockerfile
    container_name: biblioteca-bff
    ports:
      - "8080:8080"
    environment:
      - URL_FUNCION_USUARIOS=https://biblio-users-g11.azurewebsites.net/api/usuarios
      - URL_FUNCION_PRESTAMOS=https://biblio-prestamos-g11.azurewebsites.net/api/prestamos
    depends_on:
      oracle-db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  oracle-data:
