spring.application.name=bff-service
# Puerto donde correrá el BFF
server.port=8080

# URLs de las funciones Serverless inyectadas por variables de entorno.
# Si la variable de entorno no existe, usa localhost para pruebas locales.
api.usuarios.url=${URL_FUNCION_USUARIOS:http://localhost:8081}
api.prestamos.url=${URL_FUNCION_PRESTAMOS:http://localhost:8082}