-- Script de Creacion de Tablas para Sistema de Biblioteca (Oracle)
-- Se ejecuta como SYSTEM, creamos las tablas en el esquema BIBLIOTECA

-- 1. Tabla de Usuarios
CREATE TABLE biblioteca.usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    fecha_registro DATE DEFAULT SYSDATE
);

-- 2. Tabla de Libros
CREATE TABLE biblioteca.libros (
    id_libro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(200) NOT NULL,
    autor VARCHAR2(100) NOT NULL,
    disponible NUMBER(1) DEFAULT 1 CHECK (disponible IN (0, 1))
);

-- 3. Tabla de Prestamos
CREATE TABLE biblioteca.prestamos (
    id_prestamo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_libro NUMBER NOT NULL,
    fecha_prestamo DATE DEFAULT SYSDATE,
    fecha_devolucion DATE,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'DEVUELTO')),
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (id_usuario) REFERENCES biblioteca.usuarios(id_usuario),
    CONSTRAINT fk_prestamo_libro FOREIGN KEY (id_libro) REFERENCES biblioteca.libros(id_libro)
);

-- Datos de prueba
INSERT INTO biblioteca.usuarios (nombre, email) VALUES ('Sebastian Cortes', 'seba.cortesp@duocuc.cl');
INSERT INTO biblioteca.libros (titulo, autor) VALUES ('Hijo de Ladron', 'Manuel Rojas');
COMMIT;
