-- Migracion: tablas para funciones GraphQL
-- Ejecutar conectado como biblioteca@//localhost:1521/XEPDB1

-- 4. Tabla de Categorias
CREATE TABLE categorias (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion VARCHAR2(300)
);

-- 5. Tabla de Resenas
CREATE TABLE resenas (
    id_resena NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    id_libro NUMBER NOT NULL,
    calificacion NUMBER(1) NOT NULL CHECK (calificacion BETWEEN 1 AND 5),
    comentario VARCHAR2(500),
    fecha DATE DEFAULT SYSDATE,
    CONSTRAINT fk_resena_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_resena_libro FOREIGN KEY (id_libro) REFERENCES libros(id_libro)
);

-- Agregar columna de categoria a libros
ALTER TABLE libros ADD id_categoria NUMBER;
ALTER TABLE libros ADD CONSTRAINT fk_libro_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria);

-- Datos de prueba
INSERT INTO categorias (nombre, descripcion) VALUES ('Literatura Chilena', 'Obras de autores nacionales');
INSERT INTO categorias (nombre, descripcion) VALUES ('Novela', 'Ficcion narrativa larga');
INSERT INTO categorias (nombre, descripcion) VALUES ('Historia', 'Obras historicas y cronicas');

UPDATE libros SET id_categoria = 1 WHERE id_libro = 1;

INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario)
VALUES (1, 1, 5, 'Obra imprescindible de la literatura chilena');

COMMIT;
