-- Migración: tabla de auditoría para eventos de Azure Event Grid
-- Se ejecuta sobre la base de datos Oracle ya existente (luego de migration_graphql.sql)

CREATE TABLE eventos_log (
    id_evento        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento_externo VARCHAR2(100),
    tipo_evento      VARCHAR2(100) NOT NULL,
    asunto           VARCHAR2(200),
    datos            CLOB,
    fecha_recibido   DATE DEFAULT SYSDATE
);

-- Índice para filtrar por tipo de evento
CREATE INDEX idx_eventos_log_tipo ON eventos_log (tipo_evento);

COMMIT;
