-- ============================================================
-- SCHEMA COMPLETO - Sistema Biblioteca Duoc
-- Incluye todas las tablas, indices y datos de prueba
-- ============================================================

-- Limpiar tablas si existen (en orden por foreign keys)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE resenas CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE eventos_log CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE prestamos CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE libros CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE categorias CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE usuarios CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 1. Categorias
CREATE TABLE categorias (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR2(100) NOT NULL,
    descripcion  VARCHAR2(300)
);

-- 2. Usuarios
CREATE TABLE usuarios (
    id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR2(100) NOT NULL,
    email           VARCHAR2(100) UNIQUE NOT NULL,
    fecha_registro  DATE DEFAULT SYSDATE
);

-- 3. Libros (incluye stock para manejo de inventario via eventos)
CREATE TABLE libros (
    id_libro     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo       VARCHAR2(200) NOT NULL,
    autor        VARCHAR2(100) NOT NULL,
    disponible   NUMBER(1) DEFAULT 1 CHECK (disponible IN (0, 1)),
    stock        NUMBER DEFAULT 1 NOT NULL,
    id_categoria NUMBER,
    CONSTRAINT fk_libro_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria)
);

-- 4. Prestamos
CREATE TABLE prestamos (
    id_prestamo      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       NUMBER NOT NULL,
    id_libro         NUMBER NOT NULL,
    fecha_prestamo   DATE DEFAULT SYSDATE,
    fecha_devolucion DATE,
    estado           VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'DEVUELTO')),
    CONSTRAINT fk_prestamo_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_prestamo_libro   FOREIGN KEY (id_libro)   REFERENCES libros(id_libro)
);

-- 5. Resenas
CREATE TABLE resenas (
    id_resena    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario   NUMBER NOT NULL,
    id_libro     NUMBER NOT NULL,
    calificacion NUMBER(1) NOT NULL CHECK (calificacion BETWEEN 1 AND 5),
    comentario   VARCHAR2(500),
    fecha        DATE DEFAULT SYSDATE,
    CONSTRAINT fk_resena_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario),
    CONSTRAINT fk_resena_libro   FOREIGN KEY (id_libro)   REFERENCES libros(id_libro)
);

-- 6. Eventos Log
CREATE TABLE eventos_log (
    id_evento         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_evento_externo VARCHAR2(100),
    tipo_evento       VARCHAR2(100) NOT NULL,
    asunto            VARCHAR2(200),
    datos             CLOB,
    fecha_recibido    DATE DEFAULT SYSDATE
);

CREATE INDEX idx_eventos_log_tipo ON eventos_log (tipo_evento);

-- ============================================================
-- Categorias
-- ============================================================
INSERT INTO categorias (nombre, descripcion) VALUES ('Literatura Chilena', 'Obras de autores nacionales');
INSERT INTO categorias (nombre, descripcion) VALUES ('Novela', 'Ficcion narrativa larga');
INSERT INTO categorias (nombre, descripcion) VALUES ('Historia', 'Obras historicas y cronicas');
INSERT INTO categorias (nombre, descripcion) VALUES ('Ciencia Ficcion', 'Narrativa especulativa y futurista');
INSERT INTO categorias (nombre, descripcion) VALUES ('Filosofia', 'Pensamiento y teoria filosofica');
INSERT INTO categorias (nombre, descripcion) VALUES ('Poesia', 'Obras poeticas y liricas');
INSERT INTO categorias (nombre, descripcion) VALUES ('Tecnologia', 'Informatica, programacion e innovacion');
INSERT INTO categorias (nombre, descripcion) VALUES ('Economia', 'Teoria economica y finanzas');

-- ============================================================
-- Usuarios (20 usuarios)
-- ============================================================
INSERT INTO usuarios (nombre, email) VALUES ('Sebastian Cortes', 'seba.cortesp@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Nataniel Soto', 'nataniel.soto@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Camila Morales', 'camila.morales@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Diego Fuentes', 'diego.fuentes@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Valentina Reyes', 'valentina.reyes@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Andres Pizarro', 'andres.pizarro@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Isidora Vega', 'isidora.vega@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Felipe Carrasco', 'felipe.carrasco@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Javiera Munoz', 'javiera.munoz@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Nicolas Tapia', 'nicolas.tapia@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Catalina Rojas', 'catalina.rojas@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Matias Gonzalez', 'matias.gonzalez@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Daniela Herrera', 'daniela.herrera@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Cristobal Nunez', 'cristobal.nunez@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Francisca Leal', 'francisca.leal@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Ignacio Sepulveda', 'ignacio.sepulveda@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Paula Contreras', 'paula.contreras@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Roberto Alarcon', 'roberto.alarcon@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Gabriela Castro', 'gabriela.castro@duocuc.cl');
INSERT INTO usuarios (nombre, email) VALUES ('Tomas Ibarra', 'tomas.ibarra@duocuc.cl');

-- ============================================================
-- Libros (42 libros, algunos prestados stock=0, otros disponibles stock=1)
-- ============================================================

-- Literatura Chilena (cat 1)
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Hijo de Ladron', 'Manuel Rojas', 1, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('La Amortajada', 'Maria Luisa Bombal', 1, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Obsceno Pajaro de la Noche', 'Jose Donoso', 1, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Coronacion', 'Jose Donoso', 1, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Subterra', 'Baldomero Lillo', 1, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('La Ultima Niebla', 'Maria Luisa Bombal', 1, 0, 0);

-- Novela (cat 2)
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Cien Anos de Soledad', 'Gabriel Garcia Marquez', 2, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Alquimista', 'Paulo Coelho', 2, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Rayuela', 'Julio Cortazar', 2, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 2, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Crimen y Castigo', 'Fiodor Dostoievski', 2, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Gran Gatsby', 'F. Scott Fitzgerald', 2, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Anna Karenina', 'Leon Tolstoi', 2, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Orgullo y Prejuicio', 'Jane Austen', 2, 1, 1);

-- Historia (cat 3)
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Historia de Chile', 'Jorge Pinto', 3, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Sapiens', 'Yuval Noah Harari', 3, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Homo Deus', 'Yuval Noah Harari', 3, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Arte de la Guerra', 'Sun Tzu', 3, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Breve Historia del Tiempo', 'Stephen Hawking', 3, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('La Historia del Mundo en 6 Tragos', 'Tom Standage', 3, 1, 1);

-- Ciencia Ficcion (cat 4)
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('1984', 'George Orwell', 4, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Un Mundo Feliz', 'Aldous Huxley', 4, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Fundacion', 'Isaac Asimov', 4, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Dune', 'Frank Herbert', 4, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Fahrenheit 451', 'Ray Bradbury', 4, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Marciano', 'Andy Weir', 4, 0, 0);

-- Filosofia (cat 5)
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Mundo de Sofia', 'Jostein Gaarder', 5, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Asi Hablo Zaratustra', 'Friedrich Nietzsche', 5, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('La Republica', 'Platon', 5, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Meditaciones', 'Marco Aurelio', 5, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Ser y la Nada', 'Jean-Paul Sartre', 5, 0, 0);

-- Poesia (cat 6)
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Veinte Poemas de Amor', 'Pablo Neruda', 6, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Canto General', 'Pablo Neruda', 6, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Poemas y Antipoemas', 'Nicanor Parra', 6, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Residencia en la Tierra', 'Pablo Neruda', 6, 0, 0);

-- Tecnologia (cat 7)
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Clean Code', 'Robert C. Martin', 7, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('The Pragmatic Programmer', 'David Thomas', 7, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Design Patterns', 'Gang of Four', 7, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Proyecto Phoenix', 'Gene Kim', 7, 0, 0);

-- Economia (cat 8)
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('El Capital', 'Karl Marx', 8, 1, 1);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Freakonomics', 'Steven Levitt', 8, 0, 0);
INSERT INTO libros (titulo, autor, id_categoria, disponible, stock) VALUES ('Pensar Rapido Pensar Despacio', 'Daniel Kahneman', 8, 1, 1);

-- ============================================================
-- Prestamos (libros con stock=0 tienen prestamo ACTIVO)
-- ============================================================
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (1, 1, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (2, 3, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (3, 6, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (4, 7, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (5, 9, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (6, 12, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (7, 16, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (8, 19, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (9, 21, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (10, 23, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (11, 26, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (12, 28, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (13, 31, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (14, 32, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (15, 35, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (16, 36, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (17, 39, 'ACTIVO');
INSERT INTO prestamos (id_usuario, id_libro, estado) VALUES (18, 42, 'ACTIVO');

-- Prestamos devueltos (historico)
INSERT INTO prestamos (id_usuario, id_libro, fecha_devolucion, estado) VALUES (1, 7, SYSDATE - 10, 'DEVUELTO');
INSERT INTO prestamos (id_usuario, id_libro, fecha_devolucion, estado) VALUES (2, 16, SYSDATE - 5, 'DEVUELTO');
INSERT INTO prestamos (id_usuario, id_libro, fecha_devolucion, estado) VALUES (3, 21, SYSDATE - 15, 'DEVUELTO');
INSERT INTO prestamos (id_usuario, id_libro, fecha_devolucion, estado) VALUES (4, 32, SYSDATE - 3, 'DEVUELTO');
INSERT INTO prestamos (id_usuario, id_libro, fecha_devolucion, estado) VALUES (5, 35, SYSDATE - 7, 'DEVUELTO');

-- ============================================================
-- Resenas
-- ============================================================
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (1, 1, 5, 'Obra imprescindible de la literatura chilena');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (2, 7, 5, 'Una obra maestra de la ficcion latinoamericana');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (3, 9, 4, 'Cortazar en su maxima expresion creativa');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (4, 21, 5, 'Lectura obligatoria, vigente como nunca');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (5, 16, 5, 'Harari cambia la forma de ver la historia');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (6, 35, 5, 'El mejor libro de programacion que he leido');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (7, 32, 4, 'Neruda en su estado mas puro');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (8, 28, 3, 'Denso pero interesante');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (9, 23, 5, 'Asimov construye un universo increible');
INSERT INTO resenas (id_usuario, id_libro, calificacion, comentario) VALUES (10, 12, 4, 'Fitzgerald retrata una epoca con elegancia');

COMMIT;
